
#spring.profiles.active=local
# Server Port
server.port=8080

# Neon PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-round-bread-ao69rf65-pooler.c-2.ap-southeast-1.aws.neon.tech/Smart_campus?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Zp4ximhDHaU5
spring.datasource.driver-class-name=org.postgresql.Driver

Hibernate Settings (Creates your tables automatically)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# 3. Database & Hibernate Settings (NO SECRETS HERE)
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.show-sql=true

# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always