spring.profiles.active=local

# Server Port
server.port=8080

# Neon PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-round-bread-ao69rf65-pooler.c-2.ap-southeast-1.aws.neon.tech/Smart_campus?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Zp4ximhDHaU5
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings (Creates your tables automatically)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always

# ===== ADDED BY MEMBER 4 — OAuth2 & JWT =====

# Google OAuth2 Credentials
spring.security.oauth2.client.registration.google.client-id=389411629879-0lfh9m17oeisejtkc66mgp39voipq4fp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT Settings
app.jwt.secret=REPLACE_WITH_YOUR_JWT_SECRET
app.jwt.expiration-ms=86400000